from .metadata_loader_imagery_historic import MetadataLoaderImageryHistoric
from .metadata_loader_repo import MetadataLoaderRepository
from .metadata_loader_tiff import MetadataLoaderTiff

metadata_loader_rep = MetadataLoaderRepository()
metadata_loader_rep.append(MetadataLoaderImageryHistoric())
metadata_loader_rep.append(MetadataLoaderTiff())

metadata_loader_imagery_hist = MetadataLoaderImageryHistoric()
